# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["3vilpenguin@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "poopgeni.us"
service_id = "F7ywDc38d819nivD7kSXI7"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
